# -*- coding: utf-8 -*-
"""
/***************************************************************************
 plugin_info
                                 A QGIS plugin
 plugin_info
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-02-15
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Hideharu Masai
        email                : hideharumasai@void.mints.ne.jp
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt, QTimer, QObject, QEvent
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QApplication, QDialog, QDockWidget, QVBoxLayout

# Import the code for the DockWidget
from .plugin_info_dockwidget import PluginInfoDock, PluginInfoDockWidget
import os.path


class _ToolButtonDoubleClickFilter(QObject):
    """ツールバーボタンの実ウィジェットに仕込むイベントフィルタ。
    QAction.triggered はダブルクリックの2回目で必ずしも再発火しない
    （QAbstractButton側で吸収される）ため、QEvent.MouseButtonDblClick を
    直接検知する必要がある。"""

    def __init__(self, callback, parent=None):
        super().__init__(parent)
        self._callback = callback

    def eventFilter(self, obj, event):
        if event.type() == QEvent.Type.MouseButtonDblClick:
            self._callback()
        return False


class PluginInfo:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = (QSettings().value('locale/userLocale') or 'en')[:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'plugin_info_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Plugin Tools')

        self.dock = None
        self.dialog = None
        self.window = None
        self._switching_container = False
        self._dblclick_filter = None

        # ツールバーアイコンのシングル/ダブルクリック判定用。シングルクリック
        # の実行は doubleClickInterval() だけ保留し、その間に実ボタン側で
        # ダブルクリックが検知されたら（_on_toolbar_double_click）保留を
        # キャンセルしてトグル動作に切り替える。
        self._click_timer = QTimer()
        self._click_timer.setSingleShot(True)
        self._click_timer.setInterval(QApplication.doubleClickInterval())
        self._click_timer.timeout.connect(self.run)

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('PluginInfo', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action


    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(os.path.dirname(__file__), 'icon.png')
        action = self.add_action(
            icon_path,
            text=self.tr(u'Browse QGIS Plugins'),
            callback=self._on_action_triggered,
            parent=self.iface.mainWindow())

        button = self.iface.pluginToolBar().widgetForAction(action)
        if button is not None:
            self._dblclick_filter = _ToolButtonDoubleClickFilter(
                self._on_toolbar_double_click, button
            )
            button.installEventFilter(self._dblclick_filter)

# --------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""
        # The dock widget is only hidden when closed, so we don't need to do
        # anything special here. The reference is maintained.
        pass

    def _on_action_triggered(self):
        """ツールバーアイコンのクリックを処理する。すぐには実行せず、
        doubleClickInterval()の間だけ保留する。その間にダブルクリックが
        検知されれば（_on_toolbar_double_click）保留はキャンセルされる。"""
        self._click_timer.start()

    def _on_toolbar_double_click(self):
        """ツールバーの実ボタンでダブルクリックが検知されたとき（イベント
        フィルタ経由）。保留中のシングルクリック表示をキャンセルし、
        「別ウィンドウ」チェックボックスをトグルする。"""
        self._click_timer.stop()
        self._toggle_window_mode()

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        self._click_timer.stop()
        self._dblclick_filter = None

        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Plugin Tools'),
                action)
            self.iface.removeToolBarIcon(action)
        self.actions = []

        if self.window:
            self.window.cleanup()
        if self.dialog:
            self._save_dialog_geometry()
            self.dialog.hide()
            self.dialog.deleteLater()
            self.dialog = None
        if self.dock:
            self.iface.removeDockWidget(self.dock)
            self.dock.deleteLater()
            self.dock = None
        self.window = None

# --------------------------------------------------------------------------
# コンテナ生成 / 切り替え（compartment_compassと同じ方式）
# --------------------------------------------------------------------------

    def _ensure_window(self):
        if self.window is None:
            self.window = PluginInfoDockWidget(self.iface)
            self.window.set_window_mode_callback(self._set_window_mode)
            self.window.closingPlugin.connect(self.onClosePlugin)

    def _create_dock(self):
        if self.dock is not None:
            return
        self._ensure_window()
        self.dock = PluginInfoDock(self.tr('Plugin Info Browser'), self.iface.mainWindow())
        self.dock.setObjectName('PluginInfoDock')
        self.dock.setWidget(self.window)
        self.window.attach_dock_widget(self.dock)
        self.dock.setAllowedAreas(
            Qt.DockWidgetArea.LeftDockWidgetArea
            | Qt.DockWidgetArea.RightDockWidgetArea
        )
        # ネイティブ floating は無効（フロート⇔格納の遷移で透過残像バグの実績があるため）
        self.dock.setFeatures(
            QDockWidget.DockWidgetFeature.DockWidgetClosable
            | QDockWidget.DockWidgetFeature.DockWidgetMovable
        )
        self.iface.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.dock)

    def _create_dialog(self):
        if self.dialog is not None:
            return
        self._ensure_window()
        self.dialog = QDialog(None, Qt.WindowType.Window)
        self.dialog.setObjectName('PluginInfoWindow')
        self.dialog.setWindowTitle(self.tr('Plugin Info Browser'))
        self.dialog.setWindowIcon(QIcon(os.path.join(self.plugin_dir, 'icon.png')))
        layout = QVBoxLayout(self.dialog)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.addWidget(self.window)
        self.window.attach_window_dialog(self.dialog)
        self.window.show()
        geometry = QSettings().value('plugin_info/window_geometry', None)
        if geometry:
            self.dialog.restoreGeometry(geometry)
        else:
            self.dialog.resize(self.window.minimumSizeHint())
        self.dialog.finished.connect(self._on_dialog_finished)

    def _save_dialog_geometry(self):
        if self.dialog is not None:
            QSettings().setValue(
                'plugin_info/window_geometry', self.dialog.saveGeometry()
            )

    def _set_window_mode(self, enabled):
        """「別ウィンドウ」チェックボックスのトグルで呼ばれる。実体（self.window）を
        ドックと QDialog の間で付け替え、使わない側のコンテナは破棄する。"""
        self._ensure_window()
        self._switching_container = True
        try:
            if enabled:
                if self.dock is not None:
                    self.dock.setWidget(None)
                    self.iface.removeDockWidget(self.dock)
                    self.dock.deleteLater()
                    self.dock = None
                self._create_dialog()
                self.dialog.show()
                self.dialog.raise_()
                self.dialog.activateWindow()
            else:
                if self.dialog is not None:
                    self._save_dialog_geometry()
                    layout = self.dialog.layout()
                    if layout is not None:
                        layout.removeWidget(self.window)
                    self.window.setParent(None)
                    self.dialog.hide()
                    self.dialog.deleteLater()
                    self.dialog = None
                self._create_dock()
                self.window.show()
                self.dock.show()
                self.dock.raise_()
        finally:
            self._switching_container = False

    def _on_dialog_finished(self, *_args):
        if self._switching_container or self.window is None:
            return
        self._save_dialog_geometry()

    def _toggle_window_mode(self):
        currently_separate = self.dialog is not None
        self._set_window_mode(not currently_separate)

# --------------------------------------------------------------------------

    def run(self):
        """プラグインを実行する。ドックまたは別ウィンドウを表示する。"""
        if self.dialog is not None:
            self.dialog.show()
            self.dialog.raise_()
            self.dialog.activateWindow()
            return

        if self.dock is None:
            self._create_dock()

        if self.dock.isVisible():
            self.dock.raise_()
        else:
            self.dock.show()
            self.dock.raise_()
